- run.sh
issue: #3 
change package`s architecture depending on system hardware platform
> fix: change fpm option

- run.sh
fix: remove useless code from `run.sh`
> fix: remove useless code

- run.sh
[apisix/apisix#3469](https://github.com/apache/apisix/issues/3469)
> feat: add luarocks OPENSSL config

- .github/workflows/ci.yml
- Makefile
- README.md
- dockerfiles/Dockerfile.apisix.rpm
- dockerfiles/Dockerfile.dashboard.rpm
Use the new packaging scheme to package APISIX Dashboard
> feat: add packaging for apisix-dashboard

- .github/workflows/package-apisix-dashboard.yml
- .github/workflows/package-apisix.yml
feat: split the current CI, divided into APISIX part and APISIX-Dashabord part
close #26 
close #8
> feat: split the current CI

- build-apisix-openresty.sh
See https://github.com/pre-commit/action/issues/8
> fix: GitHub Action doesn't have SSH key setup.

- build-apisix-openresty.sh
And allow the script to use current directory's code instead of download
it
> feat: build apisix-nginx-module

- Makefile
- usr/lib/systemd/system/apisix.service
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
Test on CentOS7 and works
> feat: add systemd unit file to enable apisix automatically

- build-apisix-openresty.sh
ref: https://github.com/apache/apisix/issues/4396
> feat: add lua-var-nginx-module

- Makefile
- post-install-apisix-openresty.sh
> feat:  /usr/bin/{openresty,resty}

- Makefile
Created a function that builds rpm packages that helps in handling duplicate code and partly fixes the issue of optimization . #19
> feat: enhancement and minor optimization in Makefile 

- utils/install-common.sh
check apisix dir is exist before clone repo
> fix: check apisix dir is exist before clone repo

- .github/workflows/package-apisix-dashboard-el7.yml
- .github/workflows/package-apisix-dashboard-el8.yml
- .github/workflows/package-apisix-deb-default.yml
- .github/workflows/package-apisix-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-openresty-el7.yml
- .github/workflows/package-apisix-rpm-el7.yml
> feat: run ci on a regular basis

- CHANGELOG.md
This PR is going to update the `CHANGLOG` to prepare for the new release v2.2.0.
> feat: Prepare for the release v2.2.0

- CHANGELOG.md
The new release v2.2.1 will introduce two very important bug fixes and one new feature, see `CHANGE.LOG` within this PR for details.
> feat: Prepare for release v2.2.1

- CHANGELOG.md
This PR is going to update the CHANGELOG.md to prepare for the release of v2.3.0.
> feat: Update changelog for release v2.3.0

- .github/workflows/package-apisix-base-apk.yml
- dockerfiles/Dockerfile.apisix-base.apk
- utils/install-common.sh
see https://github.com/apache/apisix-docker/pull/242
> chore: add dependency in apisix-base

- dockerfiles/Dockerfile.apisix-base.apk
> chore: add openresty to PATH

- .github/workflows/publish.yml
- dockerfiles/Dockerfile.apisix-base.apk
package apisix RPM package with apisix-base.
> feat: package apisix RPM package with apisix-base

- .github/workflows/push-apisix-base-image.yml
> fix: fix the DAPISIX_BASE_VER in docker images

- package-apisix.sh
> chore: upgrade apisix-base version in package-apisix.sh

- .github/workflows/publish.yml
- utils/publish-rpm.sh
> ci: auto sign of rpm package and rpm repo metadata in CI

- utils/publish-rpm.sh
> ci: fix the correct bucket name on Aliyun OSS

- utils/publish-rpm.sh
> ci: fix the correct endpoint of Aliyun OSS

- usr/lib/systemd/system/apisix.service
1. [fix] limit config in systemd service before
2. [fix] can not enable the service
3. [add] on failure restart
4. [remove ] no useful conflicts
> feat: fix the bug and add some feature in apisix.service

- .github/workflows/push-apisix-base-image.yml
- dockerfiles/Dockerfile.apisix-base.apk
- utils/install-common.sh
A demo of the results [https://hub.docker.com/r/bzp2010/apisix-base/tags](https://hub.docker.com/r/bzp2010/apisix-base/tags)
> feat: improve apisix-base build

- build-apisix-base.sh
> chore: upgrade mod dubbo to 1.0.2

- .github/workflows/package-apisix-dashboard-rpm-el8.yml
- utils/install-common.sh
fix #165 
PR https://github.com/api7/apisix-build-tools/pull/167 need to be merged first to fix the CentOS 8 broken CI
> fix(utils): remove outdated code in utils script

- build-apisix-base.sh
fix: version: unbound variable
> fix: version: unbound variable

- build-apisix-base.sh
> feat: upgrade wasm-nginx-module to 0.5.0

- build-apisix-base.sh
> feat: upgrade apisix-nginx-module to 1.5.1

- package-apisix-base.sh
> feat: upgrade OpenSSL to 1.1.1n

- package-apisix.sh
> feat: upgrade apisix-base to 1.19.9.1.4

- build-apisix-base.sh
> feat: upgrade wasm-nginx-module to 0.5.1

- .circleci/config.yml
- utils/build-common.sh
feat(ci): support build apisix-base-deb under arm64
> feat(ci): support build apisix-base under arm64

- .circleci/config.yml
fix(ci): clarify the workflow, rename the job name
> fix(ci): clarify the workflow

- .circleci/config.yml
- Makefile
- package-apisix-base.sh
- package-apisix.sh
- test/apisix/Dockerfile.test.apisix.arm64.ubuntu20.04
- utils/install-common.sh
feat(ci): support build apisix under arm64
> feat(ci): support build apisix under arm64

- .github/workflows/package-apisix-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-rpm-el7.yml
- .github/workflows/package-apisix-rpm-el8.yml
- build-apisix-base.sh
> feat: upgrade apisix-nginx-module to 1.7.0 & wasm-nginx-module to 0.6.0

- package-apisix.sh
> feat: upgrade required apisix-base to 1.19.9.1.6

- build-apisix-base.sh
Reverts api7/apisix-build-tools#193
> Revert "feat(shdict): multi-subsystems lua_shared_dict support"

- build-apisix-base.sh
> fix: Nginx module version

- .circleci/config.yml
- dockerfiles/Dockerfile.apisix-base.deb
- utils/build-common.sh
> fix: use debian slim as base image

- build-apisix-base.sh
> feat: prepare to release APISIX-Base 1.21.4.1.1

- package-apisix.sh
> fix: specify the max version requirement of apisix-base

- build-apisix-base.sh
Currently, we only build it in the CI.
> feat: add grpc-client-nginx-module for the CI

- .github/workflows/package-apisix-base-apk.yml
- .github/workflows/package-apisix-base-deb-ubuntu20.04.yml
- build-apisix-base.sh
- dockerfiles/Dockerfile.apisix-base.apk
> feat: build with grpc engine

- build-apisix-base.sh
> fix: upgrade grpc-client-nginx-module to 0.2.1

- build-apisix-base.sh
> fix: upgrade grpc-client-nginx-module to 0.2.2

- .github/workflows/package-apisix-base-apk.yml
- .github/workflows/package-apisix-base-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-base-rpm-el7.yml
- .github/workflows/package-apisix-base-rpm-el8.yml
- build-apisix-base.sh
> feat: prepare to release apisix-base/1.21.4.1.2

- package-apisix.sh
> feat: upgrade OpenResty dependency for APISIX 3.0.0-beta

- build-apisix-base.sh
> chore: add new grpc_engine_path during the refactor of grpc-client-nginx-module

- .github/workflows/package-apisix-base-apk.yml
- .github/workflows/package-apisix-base-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-base-rpm-el7.yml
- .github/workflows/package-apisix-base-rpm-el8.yml
- build-apisix-base.sh
- package-apisix.sh
> feat: prepare to release APISIX-Base 1.21.4.1.3

- build-apisix-base.sh
Amesh is APISIX-based service mesh enhancement library
By compiling Amesh into APISIX, users can directly control whether to use this capability through configuration items.
> feat: add amesh to apisix-base

- .github/workflows/package-apisix-base-apk.yml
- .github/workflows/package-apisix-base-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-base-rpm-el7.yml
- .github/workflows/package-apisix-base-rpm-el8.yml
- build-apisix-base.sh
- package-apisix.sh
> feat: prepare to release APISIX-BASE 1.21.4.1.4

- .github/workflows/package-apisix-base-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-base-rpm-el7.yml
- .github/workflows/package-apisix-base-rpm-el8.yml
- package-apisix.sh
>  feat: prepare to release APISIX-BASE 1.21.4.1.5

- build-apisix-base.sh
The latest LuaJIT can solve:
https://github.com/apache/apisix/issues/8847
https://github.com/openresty/luajit2/issues/188
> chore: upgrade LuaJIT to the latest

- .github/workflows/publish.yml
- utils/publish-rpm.sh
Related issue: https://github.com/apache/apisix/issues/9454
> feat: publish ubi rpm package in workflows

- .github/workflows/package-apisix-base-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-base-rpm-el7.yml
- .github/workflows/package-apisix-base-rpm-el8.yml
- .github/workflows/package-apisix-base-rpm-ubi.yml
- utils/install-common.sh
add new RedHat UBI-based rpm package.
full diff: https://github.com/api7/apisix-build-tools/compare/apisix-base/1.21.4.1.8...master
> chore: release apisix-base 1.21.4.1.9

- .github/workflows/publish.yml
- utils/publish-rpm.sh
fix ci error https://github.com/api7/apisix-build-tools/actions/runs/5023950452/jobs/9009125731#step:12:150
> fix: parameter missing publish-rpm.sh

- .github/workflows/publish.yml
Fixes https://github.com/api7/apisix-build-tools/actions/runs/5026866174/jobs/9015654096#step:20:144
> fix: add dist argument in workflow

- utils/publish-rpm.sh
> fix: add repo_package_sync for centos

- utils/publish-rpm.sh
> fix: path of centos backup

- CHANGELOG.md
- build-apisix-base.sh
https://github.com/api7/apisix-build-tools/issues/328
> feat: update wasm-nginx-module 0.6.5

- build-apisix-base.sh
https://github.com/api7/grpc-client-nginx-module/issues/69
> feat: update grpc-client-nginx-module 0.4.3

- .github/workflows/publish-deb.yml
- utils/publish-deb.sh
fix: publish failed bug. 
fix: accelerates domain name failure
fix: bad file format.
> fix(ci): deb packages publishing failed

- .circleci/config.yml
- .github/workflows/package-apisix-runtime-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-runtime-rpm-el7.yml
- .github/workflows/package-apisix-runtime-rpm-el8.yml
- .github/workflows/package-apisix-runtime-rpm-ubi.yml
- .github/workflows/publish-deb.yml
- .github/workflows/publish.yml
- .github/workflows/push-apisix-runtime-image.yml
- Makefile
- README.md
- build-apisix-runtime-debug-centos7.sh
- build-apisix-runtime.sh
- dockerfiles/Dockerfile.apisix-runtime.apk
- dockerfiles/Dockerfile.apisix-runtime.deb
- dockerfiles/Dockerfile.apisix-runtime.rpm
- dockerfiles/Dockerfile.package.apisix-runtime
- package-apisix-runtime.sh
- package-apisix.sh
- post-install-apisix-runtime.sh
- utils/build-common.sh
feat: new package which name is apisix-runtime
support x86-{centos, ubi, ubuntu, alpine}
support arm-{centos, ubuntu}
> feat: support new package APISIX-runtime

- .github/workflows/publish-deb.yml
- .github/workflows/publish.yml
upload apisix-runtime Artifact
> feat: upload apisix-runtime artifact

- .github/workflows/publish.yml
fix: https://github.com/api7/apisix-build-tools/actions/runs/6955131314
> fix: modify the wrong package name

- .github/workflows/package-apisix-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-rpm-el7.yml
- .github/workflows/package-apisix-rpm-el8.yml
- .github/workflows/package-apisix-rpm-ubi.yml
- utils/install-common.sh
> chore: update the branch used by package-apisix ci to master

- .github/workflows/publish-deb.yml
https://github.com/api7/apisix-build-tools/actions/runs/7524041605/job/20478245615#step:11:20
> fix: uploading the same artifact multiple times

- README.md
fix build dashboard tag
fix issue: https://github.com/api7/apisix-build-tools/issues/315
> fix build dashboard tag

- dockerfiles/Dockerfile.fpm
fix: https://github.com/api7/apisix-build-tools/actions/runs/7956467357/job/21717242784#step:5:1031
> ci: fix fpm installation failure

- build-apisix-base.sh
- build-apisix-runtime.sh
Reverts api7/apisix-build-tools#370
> Revert "fix: remove grpc-client-nginx-module"

- .github/workflows/publish-deb.yml
- .github/workflows/publish.yml
try to fix: https://github.com/api7/apisix-build-tools/actions/runs/7985520662/job/21804131057
> fix(ci): add tag 'apisix-runtime'

- build-apisix-base.sh
- build-apisix-runtime.sh
Reverts api7/apisix-build-tools#376
> fix: remove grpc-client-nginx-module

- Makefile
needed for https://github.com/api7/apisix-build-tools/pull/392
> use arch in makefile

- build-apisix-base.sh
- build-apisix-runtime.sh
upgrade openresty to v1.27.1.1
> chore: upgrade openresty version to v1.27.1.1

- build-apisix-runtime.sh
fix: https://github.com/api7/apisix-nginx-module/actions/runs/14490471733/job/40645570601?pr=102
> chore: upgrade ngx_multi_upstream_module to fix compile error
