api7/apisix-build-tools

- README.md
- dashboard-rpm.sh
fix: move the rpm package to `output` directory
> fix: move the rpm package to output directory

- Makefile
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
For auto test ci, since the branch name would be `release/1.0`, the format - with slash `/` - is not allowed as docker image tag. So change to use argument `version` as image tag.
> chore: use version as docker image tag

- Makefile
> feat: specify apisix-openresty's dependencies

- .github/workflows/package-apisix-openresty.yml
- Makefile
- dockerfiles/Dockerfile.apisix.rpm
- dockerfiles/Dockerfile.dashboard.rpm
- dockerfiles/Dockerfile.fpm
- dockerfiles/Dockerfile.package.apisix
- dockerfiles/Dockerfile.package.apisix-dashboard
- dockerfiles/Dockerfile.package.apisix-openresty
- package-apisix-dashboard.sh
- package-apisix-openresty.sh
- package-apisix.sh
Fix: https://github.com/api7/apisix-build-tools/issues/20
What this PR does:
1. Deploy fpm using dockerfile.
2. Package apisix in  docker container and prepare for adding cache later.
> feat: use docker to deploy fpm

- utils/install-common.sh
APISIX added casbin that requires pcre, so we need to install pcre when packaging.
> fix: add pcre

- package-apisix.sh
- utils/install-common.sh
Fixes #72.
This PR is going to add `pcre` and `libpcre` as the dependencies of apisix package, which is required for lua-resty-casbin. The new package names are following the guide of lua-resty-casbin, see https://github.com/casbin-lua/lua-resty-casbin#installation.
> feat: Add pcre and libpcre as package dependencies

- .github/workflows/package-apisix-dashboard-el7.yml
- .github/workflows/package-apisix-dashboard-el8.yml
- .github/workflows/package-apisix-deb-default.yml
- .github/workflows/package-apisix-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-openresty-el7.yml
- .github/workflows/package-apisix-rpm-el7.yml
- CHANGELOG.md
This PR is going to do the preparations for the release `v2.0.0`, which contains enabling CI for tags and adding changelog. Right after this PR gets merged, I will push the tag `v2.0.0` from this commit.
Fixes https://github.com/api7/apisix-build-tools/issues/75.
> feat: Enable CI for tag v* and prepare for tag v2.0.0

- utils/install-common.sh
This PR is going to update package `ca-certificates` to avoid failure to get metalink from newly installed epel repository in CentOS 7.  See #87 for details.
Fixes #87.
> fix: failed to get metalink from epel #87

- .github/workflows/package-apisix-dashboard-el7-buildx.yml
- Makefile
- README.md
When I try to optimize apisix-dashboard's CI, I find that the build script in this repo is a reason for slow CI. As discuss in https://github.com/apache/apisix-dashboard/pull/2072, using buildx can cache Docker layers and so speed up CI.
> ci: Using Buildx as Docker builder

- utils/install-common.sh
Regarding the reason for the CI failure, it seems that the download link for `epel-release` is no longer available, and I think we should use `yum install epel-release` to install epel-release.
> fix: epel-release

- package-apisix.sh
The `config.yaml`, `config-default.yaml` and ~~`debug.yaml`~~ should be marked as config files to keep them unchanged when updating rpm/deb. This PR is going to mark the three files as `--config-files` arguments.
The `--config-files` argument is to decorate the files by the rpm directive `%config`. This will rename the original changed configuration files as `*.rpmsave`. See https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch09s05s03.html for details.
Related to https://github.com/apache/apisix/issues/5066.
> ci: Fix no setting config files

- .github/workflows/package-apisix-dashboard-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-dashboard-el7-buildx.yml
- .github/workflows/package-apisix-dashboard-rpm-el7.yml
- .github/workflows/package-apisix-dashboard-rpm-el8.yml
- .github/workflows/package-apisix-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-openresty-deb-ubuntu20.04.yml
- .github/workflows/package-apisix-openresty-rpm-el7.yml
- .github/workflows/package-apisix-rpm-el7-with-apisix-openresty.yml
Changes proposed with this PR:
1. Upload the rpms of apisix-openresty, apisix that depends on apisix-openresty;
2. Upload the debs of apisix-openresty, apisix, dashboard;
3. Bump the versions of apisix, dashboard;
> ci: Upload apisix-openresty/apisix/dashboard artifact

- utils/install-common.sh
Since the latest APISIX, from the master branch,  has already supported the ldap-auth plugin. So in order to build APISIX successfully, this PR is going to add the required openldap devel library, just as what did in https://github.com/apache/apisix-docker/pull/222.
> fix: Add ldap dev dependency for building apisix

- package-apisix.sh
Fixes #135.
The `which` command is used by the apisix startup script. So this PR is going to add `which` as the dependency of APISIX to ensure we can start apisix without any error.
> fix: add which as dependency of apisix

- .github/workflows/package-apisix-rpm-el7-with-apisix-base.yml
- build-apisix-base.sh
- package-apisix.sh
See https://github.com/api7/apisix-build-tools/runs/4713215166?
check_suite_focus=true
> ci: use latest apisix-base with latest apisix

- utils/install-common.sh
Update luarocks to v3.8.0 for resolve the `git://` will be disabled.
> chore: update luarocks to v3.8.0

- build-apisix-base.sh
Turn out we don't need it for ASAN build.
> Revert "feat: allow building with extra args"

- dockerfiles/Dockerfile.dashboard.deb
- dockerfiles/Dockerfile.dashboard.rpm
- utils/install-common.sh
use environment variable for goproxy
fix #177
> ci: use environment variable for goproxy

- .github/workflows/publish.yml
- utils/publish-rpm.sh
Now CI will upload the repo directly to CI bucket instead of production bucket, then copy the CI bucket to the production bucket to reduce the service unavailability time.
> feat: add ci repo support

- build-apisix-base.sh
Add version for module dir, so that `openresty -V` will be able to see the version number of the module
> feat: add version for module dir

- utils/publish-rpm.sh
success build CI:https://github.com/tzssangglass/apisix-build-tools/runs/7068733499?check_suite_focus=true
download link: https://apisix-repo-1312610933.cos.ap-nanjing.myqcloud.com/packages/centos/7/x86_64/apisix-2.13.2-0.el7.x86_64.rpm
> chore: fix folder path and exception exit

- dockerfiles/Dockerfile.apisix-base.deb
- dockerfiles/Dockerfile.package.apisix
- dockerfiles/Dockerfile.package.apisix-base
- dockerfiles/Dockerfile.package.apisix-dashboard
- package-apisix-base.sh
- utils/determine-dist.sh
Get codemae when building, not when you packaging. This ensures that the correct openresty dependency package information is written when packaging.
> fix: incorrect codename when packaging

- .circleci/config.yml
- .github/workflows/publish-deb.yml
Upload deb package to artifacts only, for circleci cant't upload debian package file to cos.
> chore: upload deb package to artifacts only

- dockerfiles/Dockerfile.dashboard.deb
- dockerfiles/Dockerfile.dashboard.rpm
Remove the default GOPROXY value used when building the APISIX Dashboard, it will break our CI build process.
It turns out that we use the proxy service provided by `https://proxy.golang.com.cn`, which often responds with `502 Bad Gateway` in GitHub CI and fails to provide normal service.
> fix: remove the default value of goproxy

- .github/workflows/publish.yml
Since createrepo is deprecated in the latest ubuntu 20.04 version, use ubuntu 18.04 as a temporary solution.
We will look for alternatives to createrepo in the future.
> fix: unable to locate package createrepo

- .github/workflows/publish.yml
Currently this[1] github action is failing due to timeout. This PR increases the timeout to fix it. 
1. https://github.com/api7/apisix-build-tools/actions/runs/5025121515
> fix: Increase timeout for publish job

- .github/workflows/publish-deb.yml
- .github/workflows/publish.yml
- utils/publish-deb.sh
- utils/publish-rpm.sh
- support upload with deb
- replace coscli with coscmd
- Use globally accelerated domain names to improve upload speed.
- Fix  `--part-size` too large causing slow upload speed.
test ci run:
https://github.com/api7/apisix-build-tools/actions/runs/5782463840/job/15669335847
> chore(ci): replace coscli with coscmd

- build-apisix-base.sh
There are some dependencies that will run `build-apisix-base.sh`.
For example, when upgrading to openrsty for `apisix-nginx-module`, 
CI operation relies on `build-apisix-base.sh`, due to hard coding, the file content can only be forcibly replaced.
> chore: definable of openresty version

- .github/workflows/publish-deb.yml
3.5.0 deb
```yaml
Package: apisix
Version: 3.5.0-0
License: ASL 2.0
Vendor: none
Architecture: amd64
Maintainer: <@buildkitsandbox>
Installed-Size: 14342
Depends: openresty (>= 1.19.3.2), openresty (<< 1.21.5), libldap2-dev, libpcre3, debianutils
Section: default
Priority: optional
Homepage: http://apisix.apache.org/
Description: Apache APISIX is a distributed gateway for APIs and Microservices, focused on high performance and reliability.
```
> fix(ci): apisix should rely on apisix-base instead of openresty

- build-apisix-base.sh
Remove amesh from apisix-base because it is not necessary for APISIX.
> change: remove amesh from apisix-base

- build-apisix-runtime.sh
https://github.com/apache/apisix/issues/10431
> feat: lua resty events

- utils/install-common.sh
Due to pr: https://github.com/apache/apisix/pull/10441
We need to change the path of apisix's rockspec file
> chore: change the apisix rockspec file path

- usr/lib/systemd/system/apisix.service
ref: https://github.com/apache/apisix/pull/10732
The files being exposed by container mounts and not being cleaned up on abnormal exits resulting in failure to start next time.
> fix: apisix startup failed due to unix socket not being removed

- utils/install-common.sh
As we can see in the picture, the CI will fail because of `error An unexpected error occurred: "https://registry.npm.taobao.org/state-local/download/state-local-1.0.7.tgz: certificate has expired".`
Now we don't have any method to let upstream update the `certificate`, so we can set `strict-ssl` to false to avoid verifying the certificate.
> fix: dashboard ci

- build-apisix-base.sh
- build-apisix-runtime.sh
In APISIX, a Golang library was previously used to effectively implement a gRPC client and bind it to the Nginx ecosystem. It is called [grpc-client-nginx-module](https://github.com/api7/grpc-client-nginx-module). APISIX no longer uses this, it was removed in the PR https://github.com/apache/apisix/pull/9456. This PR removes it from the build-tools
> fix: remove grpc-client-nginx-module

- build-apisix-base.sh
- build-apisix-runtime.sh
related PRs
- https://github.com/api7/ngx_multi_upstream_module/pull/12
- https://github.com/api7/ngx_multi_upstream_module/pull/13
- https://github.com/api7/grpc-client-nginx-module/pull/73
- https://github.com/api7/wasm-nginx-module/pull/162
- https://github.com/api7/apisix-nginx-module/pull/83
> feat: upgrade to openresty-1.25.3.1

- README.md
`build-apisix-runtime-apk` already removed in https://github.com/api7/apisix-build-tools/pull/358, update docs to reflect the change.
> fix: remove outdated apisix-runtime-apk build construction from docs

- dockerfiles/Dockerfile.fpm
This dependency is present in master branch and building it in openresty/1.21.4 branch results in error
https://github.com/api7/apisix-build-tools/blob/92d40ebda2d047ed51db6c1cb41f44410d98e319/dockerfiles/Dockerfile.fpm#L6C5-L6C37
> ci: install missing dependency to build image(openresty/1.21.4 branch)

- build-api7ee-runtime.sh
`In LuaJit version 2.1-20240815, some performance and security issues have been fixed. OpenResty version 1.27.1.1 has already used this version, and we hope that the enterprise version will also be upgraded to this version.`
LuaJIT updated to 2.1-20240815 with various optimizations and bugfixes:
```
Improved error handling and stack overflow management
Enhanced cross-32/64 bit and deterministic bytecode generation
Disabled hash computation optimization in the OpenResty branch due to potential severe performance degradation (CVE-2024-39702). This issue only exists in the OpenResty branch (agentzh-v2.1) and not in upstream LuaJIT. We thank Zhongwei Yao from Kong Inc. for reporting this issue.
```
> upgrade: luajit to version 2.1-20240815
